# TRAE AI IDE Configuration
# Comprehensive configuration for AI-assisted development

trae:
  version: "1.0.0"
  
  # AI Engine Configuration
  ai:
    enabled: true
    provider: "trae-ai"
    
    # AI Models Configuration
    models:
      codeGeneration:
        model: "trae-codegen-v2"
        temperature: 0.2
        maxTokens: 2000
        contextWindow: 8000
      
      codeReview:
        model: "trae-review-v1"
        temperature: 0.1
        maxTokens: 1000
        contextWindow: 4000
      
      documentation:
        model: "trae-docs-v1"
        temperature: 0.3
        maxTokens: 1500
        contextWindow: 6000
      
      testing:
        model: "trae-test-v1"
        temperature: 0.2
        maxTokens: 1500
        contextWindow: 5000
    
    # Code Completion Settings
    completion:
      enabled: true
      multiline: true
      contextLength: 5000
      triggerDelay: 100
      quality: "high"
      diversity: true
      cacheEnabled: true
      
    # Chat Interface Settings
    chat:
      enabled: true
      contextAware: true
      codebaseIntegration: true
      maxHistory: 100
      multiAgent: true
      
    # Code Analysis Configuration
    analysis:
      enabled: true
      deepAnalysis: true
      semanticUnderstanding: true
      crossFileAnalysis: true
      dependencyTracking: true
      performanceOptimization: true
      securityAnalysis: true

  # Agent Configuration
  agents:
    enabled: true
    directory: ".trae/agents"
    maxConcurrent: 4
    
    # Agent Collaboration Settings
    collaboration:
      enabled: true
      coordinationStrategy: "consensus"
      conflictResolution: "vote"
      sharedContext: true
      
    # Specialized Agents
    specialization:
      productPlanning: true
      codeArchitecture: true
      implementation: true
      qualityAssurance: true
      documentation: true
      debugging: true

  # Workflow Configuration
  workflows:
    enabled: true
    directory: ".trae/workflows"
    autoTrigger: true
    
    # Workflow Triggers
    triggers:
      fileChanges:
        - "src/**/*.js"
        - "src/**/*.ts"
        - "src/**/*.jsx"
        - "src/**/*.tsx"
        - "src/**/*.py"
        - "src/**/*.java"
        - "src/**/*.go"
        - "src/**/*.rs"
        - "src/**/*.cpp"
        - "src/**/*.c"
      
      gitEvents:
        - "commit"
        - "push"
        - "pull_request"
        - "merge"
      
      schedules:
        - "daily"
        - "weekly"
      
      customTriggers: []
    
    # Workflow Conditions
    conditions:
      fileSize: "< 1MB"
      complexity: "< high"
      testCoverage: "> 70%"
      
    # Automation Settings
    automation:
      codeGeneration: true
      testing: true
      documentation: true
      codeReview: true
      deployment: false  # Requires manual approval

  # Prompt Configuration
  prompts:
    directory: ".trae/prompts"
    autoLoad: true
    customPrompts: true
    promptTemplates: true
    versionControl: true

# Editor Configuration
editor:
  fontSize: 14
  fontFamily: "'Fira Code', 'JetBrains Mono', 'Cascadia Code', Consolas, monospace"
  fontLigatures: true
  lineHeight: 1.5
  tabSize: 2
  insertSpaces: true
  detectIndentation: true
  wordWrap: "on"
  
  # Minimap Settings
  minimap:
    enabled: true
    maxColumn: 120
  
  # Editor Rules and Guides
  rulers: [80, 120]
  
  # Auto-formatting
  formatOnSave: true
  formatOnPaste: true
  
  # Code Actions
  codeActions:
    onSave:
      fixAll: true
      organizeImports: true
      addMissingImports: true
      removeUnusedImports: true
  
  # Inline Suggestions
  inlineSuggest:
    enabled: true
    showToolbar: "onHover"
    
  # Suggestion Settings
  suggest:
    preview: true
    showInlineDetails: true
    
  # Quick Suggestions
  quickSuggestions:
    other: "on"
    comments: "on"
    strings: "on"

# File Management
files:
  autoSave: "afterDelay"
  autoSaveDelay: 1000
  trimTrailingWhitespace: true
  insertFinalNewline: true
  
  # File Exclusions
  exclude:
    - "**/node_modules"
    - "**/dist"
    - "**/build"
    - "**/.git"
    - "**/.DS_Store"
    - "**/coverage"
    - "**/.next"
    - "**/.nuxt"
    - "**/out"
    - "**/.trae/cache"

# Workbench Configuration
workbench:
  colorTheme: "TRAE Dark Pro"
  iconTheme: "trae-icons"
  
  editor:
    enablePreview: false
    closeOnFileDelete: true
    
  startupEditor: "welcomePage"
  
  # Command Palette
  commandPalette:
    experimental:
      suggestCommands: true

# Terminal Configuration
terminal:
  integrated:
    fontSize: 13
    fontFamily: "'Fira Code', 'JetBrains Mono', Consolas, monospace"
    
    # Default Profiles
    defaultProfile:
      windows: "PowerShell"
      osx: "zsh"
      linux: "bash"

# Version Control
git:
  enableSmartCommit: true
  confirmSync: false
  autofetch: true
  showPushSuccessNotification: true
  suggestSmartCommit: true
  
  # AI-Powered Git Features
  aiCommitMessages: true
  aiMergeConflictResolution: true
  aiCodeReview: true

# Language-Specific Settings
languages:
  typescript:
    preferences:
      quoteStyle: "single"
    suggest:
      autoImports: true
    updateImportsOnFileMove: "always"
    inlayHints:
      parameterNames: "all"
      variableTypes: true
      functionLikeReturnTypes: true
      
  javascript:
    preferences:
      quoteStyle: "single"
    suggest:
      autoImports: true
    updateImportsOnFileMove: "always"
    inlayHints:
      parameterNames: "all"
      variableTypes: true
      functionLikeReturnTypes: true
      
  python:
    formatting:
      provider: "black"
    linting:
      enabled: true
      provider: "pylint"
    typeChecking:
      enabled: true
      provider: "mypy"

# Linting Configuration
linting:
  eslint:
    validate:
      - "javascript"
      - "javascriptreact"
      - "typescript"
      - "typescriptreact"
      - "vue"
      - "html"
      - "markdown"
    format:
      enable: true
    
  # AI-Powered Linting
  aiLinting:
    enabled: true
    severity: "warning"
    autoFix: true

# Formatting Configuration
formatting:
  prettier:
    singleQuote: true
    trailingComma: "es5"
    tabWidth: 2
    semi: true
    printWidth: 100
    bracketSpacing: true
    arrowParens: "avoid"
    
  # AI-Powered Formatting
  aiFormatting:
    enabled: true
    style: "consistent"
    optimization: true

# Search Configuration
search:
  exclude:
    - "**/node_modules"
    - "**/dist"
    - "**/build"
    - "**/coverage"
    - "**/.git"
    - "**/.trae/cache"
    
  # AI-Powered Search
  aiSearch:
    enabled: true
    semanticSearch: true
    contextualResults: true

# Performance Configuration
performance:
  indexing:
    incremental: true
    background: true
    intelligent: true
    
  caching:
    enabled: true
    strategy: "intelligent"
    maxSize: "1GB"
    
  memoryOptimization: true
  
  # AI Performance Settings
  aiPerformance:
    batchProcessing: true
    parallelExecution: true
    resourceOptimization: true

# Integration Configuration
integrations:
  github:
    enabled: true
    autoSync: true
    prAnalysis: true
    issueTracking: true
    
  docker:
    enabled: true
    autoDetection: true
    
  kubernetes:
    enabled: false
    
  testing:
    frameworks:
      - "jest"
      - "mocha"
      - "pytest"
      - "junit"
      - "cypress"
      - "playwright"
    autoRun: false
    coverage: true
    aiTestGeneration: true
    
  cicd:
    providers:
      - "github-actions"
      - "gitlab-ci"
      - "jenkins"
    autoConfiguration: true
    
  monitoring:
    enabled: true
    providers:
      - "datadog"
      - "newrelic"
      - "prometheus"

# Security Configuration
security:
  enabled: true
  
  # Code Security Analysis
  codeAnalysis:
    vulnerabilityScanning: true
    dependencyChecking: true
    secretDetection: true
    
  # AI Security Features
  aiSecurity:
    secureCodeGeneration: true
    vulnerabilityPrevention: true
    securityRecommendations: true

# Extensions Configuration
extensions:
  autoUpdate: true
  ignoreRecommendations: false
  
  # AI-Powered Extension Management
  aiExtensions:
    smartRecommendations: true
    autoInstall: false
    compatibilityChecking: true

# Debugging Configuration
debugging:
  console:
    fontSize: 13
    fontFamily: "'Fira Code', 'JetBrains Mono', Consolas, monospace"
    
  # AI-Powered Debugging
  aiDebugging:
    enabled: true
    smartBreakpoints: true
    errorAnalysis: true
    solutionSuggestions: true

# Telemetry and Analytics
telemetry:
  enabled: true
  anonymous: true
  
  # Usage Analytics
  analytics:
    productivityMetrics: true
    aiUsageStats: true
    performanceMetrics: true